// === CONSTRAINTS ===
CREATE CONSTRAINT author_id IF NOT EXISTS ON (a:Author) ASSERT a.id IS UNIQUE;
CREATE CONSTRAINT publisher_id IF NOT EXISTS ON (p:Publisher) ASSERT p.id IS UNIQUE;
CREATE CONSTRAINT genre_id IF NOT EXISTS ON (g:Genre) ASSERT g.id IS UNIQUE;
CREATE CONSTRAINT book_id IF NOT EXISTS ON (b:Book) ASSERT b.id IS UNIQUE;
CREATE CONSTRAINT customer_id IF NOT EXISTS ON (c:Customer) ASSERT c.id IS UNIQUE;

